# Site settings
# GitHub Pages will build with this theme automatically
# See: https://pages.github.com/themes/

title: "Linwei Chen 陈霖炜"
description: "Engineering, systems, and ML notes — projects and writing"
# Professional, clean theme
theme: jekyll-theme-cayman

# Author / social
author: "Linwei Chen"
email: ""
github_username: linweic
linkedin_username: linweic

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Use the same theme layout for all pages and posts
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
