# Site settings
# GitHub Pages will build with this theme automatically
# See: https://pages.github.com/themes/

title: "Linwei Chen 陈霖炜"
description: "Engineering, systems, and ML notes — projects and writing"
# Professional, clean theme
theme: jekyll-theme-cayman

# Author / social
author: "Linwei Chen"
email: ""
github_username: linweic
linkedin_username: linweic

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Add defaults to inject custom head include on all pages via content
# Cayman theme uses a simple layout; we can include head via a custom includes in pages content.
# We'll reference it explicitly in pages where needed.

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
